import { generateDailyBriefing } from "@/lib/insights";
import { veniceChat } from "@/lib/venice";

export async function POST(req) {
  try {
    const { congressData, format } = await req.json();
    if (!congressData) return Response.json({ error: "Missing congressData" }, { status: 400 });

    // Generate the briefing
    const briefing = await generateDailyBriefing(congressData);

    if (format === "json") {
      return Response.json(briefing);
    }

    // For PDF/text export, format as markdown
    const model = process.env.VENICE_MODEL_REASONING || "kimi-k2-5";
    const markdownContent = formatBriefingAsMarkdown(briefing);

    if (format === "markdown" || format === "text") {
      return new Response(markdownContent, {
        headers: {
          "Content-Type": format === "markdown" ? "text/markdown" : "text/plain",
          "Content-Disposition": `attachment; filename="briefing-${Date.now()}.md"`,
        },
      });
    }

    // Default: return JSON
    return Response.json(briefing);
  } catch (e) {
    return Response.json({ error: e.message }, { status: 500 });
  }
}

function formatBriefingAsMarkdown(briefing) {
  let md = "# Congress Daily Briefing\n\n";

  if (briefing.headline) {
    md += `## ${briefing.headline}\n\n`;
  }

  if (briefing.summary) {
    md += `${briefing.summary}\n\n`;
  }

  if (briefing.key_insights?.length) {
    md += "## Key Insights\n\n";
    for (const insight of briefing.key_insights) {
      md += `- **[${insight.importance || "N/A"}/5]** ${insight.insight} _(${insight.category || "General"})_\n`;
    }
    md += "\n";
  }

  if (briefing.watch_sessions?.length) {
    md += "## Sessions to Watch\n\n";
    for (const s of briefing.watch_sessions) {
      md += `- **${s.title}** (ID: ${s.session_id}) — ${s.reason}\n`;
    }
    md += "\n";
  }

  if (briefing.emerging_topics?.length) {
    md += `## Emerging Topics\n\n${briefing.emerging_topics.map((t) => `- ${t}`).join("\n")}\n\n`;
  }

  if (briefing.action_items?.length) {
    md += "## Action Items\n\n";
    for (const item of briefing.action_items) {
      md += `- ${item}\n`;
    }
    md += "\n";
  }

  md += `\n---\n_Generated by CongressAI — ${new Date().toISOString()}_\n`;
  return md;
}